name: Build Packages
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install APT packages
        run: sudo apt install python3 python3-yaml

      - name: Run tests
        run: ./test.bash

      - name: Build pacman packages
        uses: pacman-repo-builder/action@0.0.0-rc.64
        with:
          command: |
            set -o errexit -o pipefail -o nounset
            build-pacman-repo build

      - name: Inspect changed failed build record
        continue-on-error: true
        run: cat failed-build-records.yaml

      - name: List changes
        run: |
          pwd
          ls
          echo "================="
          git status

      - name: Upload packages
        env:
          AUTH: ${{ secrets.AUTH }}
        run: |          
          git config user.name rzlamrr
          git config user.email rzlamrr.dvst@protonmail.com
          git add -v repo/
          git commit -m "Update by $GITHUB_REPOSITORY@$GITHUB_SHA" --allow-empty
          git pull origin master --rebase=true # to avoid conflicts due to data races
          git push https://rzlamrr:$AUTH@github.com/rzlamrr/pacman-repo master